services:
  zenohd:
    build: .
    image: ghcr.io/pojiro/giocci_zenohd:1.7.1
    working_dir: /root/giocci
    volumes:
      - .:/root/giocci
    ports:
      - "7447:7447"
      - "7446:7446/udp"
    restart: unless-stopped
