services:
  giocci_engine:
    image: ghcr.io/pojiro/giocci_engine:0.1.0
    build:
      context: ../../
      dockerfile: apps/giocci_engine/Dockerfile
    volumes:
      - ./config/giocci_engine.exs:/root/giocci_engine/giocci_engine.exs:ro
      - ./config/zenoh.json:/root/giocci_engine/zenoh.json:ro
    restart: "always"
