services:
  giocci_relay:
    image: ghcr.io/biyooon-ex/giocci/giocci_relay:0.3.0
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./config/giocci_relay.exs:/app/giocci_relay.exs:ro
      - ./config/DEFAULT_CONFIG.json5:/app/zenoh.json:ro
    restart: "always"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
