services:
  giocci_client:
    image: ghcr.io/pojiro/giocci_client:0.1.0
    build:
      context: ../../
      dockerfile: apps/giocci_client/Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./config/giocci_client.exs:/root/giocci_client/giocci_client.exs:ro
      - ./config/zenoh.json:/root/giocci_client/zenoh.json:ro
    restart: "always"
