services:
  giocci_client:
    image: ghcr.io/biyooon-ex/giocci/giocci_client:0.3.0
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./config/giocci_client.exs:/app/giocci_client.exs:ro
      - ./config/DEFAULT_CONFIG.json5:/app/zenoh.json:ro
    restart: "always"
    stdin_open: true
    tty: true
